objects/Coin__c/Coin__c.object-meta.xml
<CustomObject>
    <label>Moeda</label>
    <nameField>
        <label>Sigla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moedas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Coin__c/fields/id_api__c.field-meta.xml
<CustomField>
    <fullName>id_api__c</fullName>
    <label>ID API</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

classes/getAllCoinStats_Controller.cls
public class getAllCoinStats_Controller {

    private List<Coin__c> coinList {get; set;}
    public ApexPages.StandardSetController stdControl{get; set;}
    
    // Construtor
    public getAllCoinStats_Controller(ApexPages.StandardSetController controller) {
        stdControl = controller;
        // Preenche lista somente com moedas que possuem id da API
        this.coinList = [SELECT Id, Name, id_api__c FROM Coin__c WHERE id_api__c != null];
    }

    // Codigo chamado ao carregar pagina.
    public PageReference autoRun_getAllCoinStats() {
        
        try {
            // Se nao houver registros mostra pagina VF com msg de erro
            if (this.coinList.isEmpty()) {            
                return null; 
            }
            
            // Chama funcao para atualizar informacoes das moedas
            Cripto.getAllCoinsMarketData(this.coinList);
        }
        catch(Exception e) {
            system.debug('ERROR: '+ e);
        }

        Schema.DescribeSObjectResult result = Coin__c.SObjectType.getDescribe(); 
        PageReference pageRef = new PageReference('/' + result.getKeyPrefix()); 
        pageRef.setRedirect(true); 
        return pageRef; 

        
    }
    
}